apiVersion: v1
kind: Service
metadata:
  name: flask-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: flask-app-dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer